---
title: "R Notebook"
output: html_notebook
---

```{r}
library('dplyr')
library('jsonlite')
library('readr')
library('tidyr')
options(scipen=999)

data <- read.csv('Data for Major Studio Final Project (2)/03f01820-19db-4cfa-98e5-045d34841cd7_Data.csv')
glimpse(data)

meta<- read.csv('Data for Major Studio Final Project (2)/03f01820-19db-4cfa-98e5-045d34841cd7_Country - Metadata.csv')
glimpse(meta)
```

```{r}
# get region
merged <- merge(data, meta, by.x = 'Country.Code', by.y = 'Code')
merged <- merged[merged$Region == 'Sub-Saharan Africa',]
summary(merged)
glimpse(merged)

# test<- merged %>% select(Country.Name, Country.Code, Time)

country_data <- merged %>%
  select(Country.Name, Country.Code, Time, Agricultural.irrigated.land....of.total.agricultural.land...AG.LND.IRIG.AG.ZS., Agricultural.machinery..tractors..AG.AGR.TRAC.NO., Agricultural.machinery..tractors.per.100.sq..km.of.arable.land..AG.LND.TRAC.ZS., Agriculture.value.added.per.worker..constant.2010.US....EA.PRD.AGRI.KD., Agricultural.land....of.land.area...AG.LND.AGRI.ZS., Agriculture..value.added..annual...growth...NV.AGR.TOTL.KD.ZG., Depth.of.the.food.deficit..kilocalories.per.person.per.day...SN.ITK.DFCT., Food.exports....of.merchandise.exports...TX.VAL.FOOD.ZS.UN., Food.imports....of.merchandise.imports...TM.VAL.FOOD.ZS.UN., Fertilizer.consumption....of.fertilizer.production...AG.CON.FERT.PT.ZS., Fertilizer.consumption..kilograms.per.hectare.of.arable.land...AG.CON.FERT.ZS., Rural.poverty.gap.at.national.poverty.lines......SI.POV.RUGP., Employment.in.agriculture....of.total.employment...SL.AGR.EMPL.ZS., Rural.population....of.total.population...SP.RUR.TOTL.ZS.,
Income.share.held.by.lowest.10...SI.DST.FRST.10.,
Income.share.held.by.lowest.20...SI.DST.FRST.20.,
Account..income..poorest.40.....ages.15....ts...WP_time_10.8.,
GDP..current.US....NY.GDP.MKTP.CD.,
Population..total..SP.POP.TOTL., 
Arable.land..hectares...AG.LND.ARBL.HA.,
Land.area..sq..km...AG.LND.TOTL.K2.,
Rural.poverty.headcount.ratio.at.national.poverty.lines....of.rural.population...SI.POV.RUHC.,
Long.Name,
Access.to.electricity..rural....of.rural.population...EG.ELC.ACCS.RU.ZS.,
People.using.basic.drinking.water.services..rural....of.rural.population...SH.H2O.BASW.RU.ZS.,
Employment.in.agriculture....of.total.employment...SL.AGR.EMPL.ZS.  
# GINI.index..World.Bank.estimate...SI.POV.GINI.
) %>%
  rename(AgriValuePerWorker = Agriculture.value.added.per.worker..constant.2010.US....EA.PRD.AGRI.KD.,
        RuralPovGap = Rural.poverty.gap.at.national.poverty.lines......SI.POV.RUGP., 
        RuralPopPerc = Rural.population....of.total.population...SP.RUR.TOTL.ZS.,
        FoodDeficit = Depth.of.the.food.deficit..kilocalories.per.person.per.day...SN.ITK.DFCT.,
        IrrigatedLandPerc = Agricultural.irrigated.land....of.total.agricultural.land...AG.LND.IRIG.AG.ZS.,
        TractorsNum = Agricultural.machinery..tractors..AG.AGR.TRAC.NO.,
        TractorsRel = Agricultural.machinery..tractors.per.100.sq..km.of.arable.land..AG.LND.TRAC.ZS.,
        FoodExportsP = Food.exports....of.merchandise.exports...TX.VAL.FOOD.ZS.UN.,
        FoodImportsP = Food.imports....of.merchandise.imports...TM.VAL.FOOD.ZS.UN., 
        FertilizerConsump = Fertilizer.consumption....of.fertilizer.production...AG.CON.FERT.PT.ZS., 
        FertilizerConsumpPerHA = Fertilizer.consumption..kilograms.per.hectare.of.arable.land...AG.CON.FERT.ZS.,
        EmployInAg = Employment.in.agriculture....of.total.employment...SL.AGR.EMPL.ZS.,
        Country = Country.Name, 
        IncomeShareLowest10 = Income.share.held.by.lowest.10...SI.DST.FRST.10., 
        IncomeShareLowest20 = Income.share.held.by.lowest.20...SI.DST.FRST.20., 
        Population_total = Population..total..SP.POP.TOTL.,
        GDP = GDP..current.US....NY.GDP.MKTP.CD.,
        ArableLandHectares = Arable.land..hectares...AG.LND.ARBL.HA.,
        LandAreaSqMeters = Land.area..sq..km...AG.LND.TOTL.K2.,
        RuralPovertyRatio = Rural.poverty.headcount.ratio.at.national.poverty.lines....of.rural.population...SI.POV.RUHC.,
        RuralElectricityAccess = Access.to.electricity..rural....of.rural.population...EG.ELC.ACCS.RU.ZS.,
        RuralWaterServicesAccess = People.using.basic.drinking.water.services..rural....of.rural.population...SH.H2O.BASW.RU.ZS.,
        EmploymentShareInAg = Employment.in.agriculture....of.total.employment...SL.AGR.EMPL.ZS.  
        # Gini = GINI.index..World.Bank.estimate...SI.POV.GINI.
        )
#TODO: add more variabel aliases

glimpse(country_data)
```

adding gini scores
```{r}
gini <- read_csv('Income inequality, Gini coefficient.csv', skip = 1)
# gini <- rename(gini, '2010' = 'X2010')
# gini <- rename(gini, '2011' = 'X2011')
# gini <- rename(gini, '2012' = 'X2012')
# gini <- rename(gini, '2013' = 'X2013')
# gini <- rename(gini, '2014' = 'X2014')
# gini <- rename(gini, '2015' = 'X2015')
# head(gini)
# glimpse(gini)
View(gini)

gini_new <- gather(gini,'Time', 'Gini', 3: 13, na.rm = TRUE)
gini_new$Time = as.character(gini_new$Time)
gini_new$Country = as.character(gini_new$Country)
gini_new$Gini = as.numeric(gini_new$Gini)
gini_new = gini_new %>% select('Country', 'Time', 'Gini')

# head(gini_new)

country_data$Time = as.character(country_data$Time)
country_data$Country = as.character(country_data$Country)

# head(country_data)
country_data_with_gini <- left_join(country_data, gini_new, by = c("Country", "Time"))
View(country_data_with_gini)
country_data <- country_data_with_gini
glimpse(country_data)
```

getting averages for Rural Pov, Rural Pov Gap, Gini
```{r}
indicator_averages <- country_data %>%
  group_by(Country) %>%
  summarise(avgGini = mean(as.numeric(Gini), na.rm = TRUE), avgRuralPovRatio = mean(RuralPovertyRatio, na.rm = TRUE), avgRuralPovGap = mean(RuralPovGap, na.rm = TRUE))

country_data <- left_join(country_data, indicator_averages, by= "Country")
glimpse(country_data)
# summary(indicator_averages)

```

getting crop distribution for each country
```{r}
crops <- read.csv('CpC2.csv')
# glimpse(crops)
# summary(crops)
# crops <- crops[order(crops$Area, crops$Year, crops$Item),]
# View(crops)
# grouped_crops <- group_by(crops, crops$Area, crops$Year)

# gets the total number of crops for each country/year
grouped_summary <- crops %>%
  group_by(Area, Year) %>%
  summarise(totalValue = sum(Value, na.rm= TRUE))

# View(grouped_summary)

# add total column to full data
merged_crops <- left_join(crops, grouped_summary, by= c("Area", "Year"))

# calculate % of total
merged_crops$percentOfTotal<- merged_crops$Value/merged_crops$totalValue
merged_crops = merged_crops[order(merged_crops$Area, merged_crops$Year, -merged_crops$percentOfTotal),]

# View(grouped_summary)
# View(merged_crops)

# get top 10 crops
top_crops <- merged_crops %>%
  group_by(Area, Year) %>%
  filter(row_number() <= 5) %>%
  select(Area, Year, Unit, Value, Item, totalValue, percentOfTotal)

top_crops_top_summary <- top_crops %>%
  group_by(Area, Year) %>%
  summarise(subtotalValue = sum(Value, na.rm= TRUE))


merged_top_crops<- left_join(top_crops, top_crops_top_summary, by = c("Area", "Year"))
merged_top_crops$percentOfSubtotal<- merged_top_crops$Value/merged_top_crops$subtotalValue

View(merged_top_crops)

crops_with_Other_row<- merged_top_crops %>%
   group_by(Area, Year) %>%
   summarise(Value = last(totalValue)-last(subtotalValue), totalValue = last(totalValue)) %>%
   mutate(Item = "Other", percentOfTotal = Value/totalValue, percentOfSubtotal = NA) %>% 
   bind_rows(merged_top_crops, .) %>% 
   arrange(Area, Year)

# View(crops_with_other_row)
crops_with_Other_row$Year = as.character(crops_with_Other_row$Year)
# glimpse(merged_top_crops)

# glimpse(country_data)

final_crop_data <- right_join(country_data, crops_with_Other_row, by= c ("Country" = "Area", "Time" = "Year"))

glimpse(final_crop_data[final_crop_data$Time >= 2010,])

final_crop_data <- final_crop_data %>% 
  filter(Time >= 2010) %>%
  toJSON() %>%
  write_lines('cropdata.json')

```

